import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  weights: [400, 500, 600, 700],
  subsets: ["latin"],
  variable: "--font--montserrat",
});

export const metadata = {
  title: "Movies Enthusiast",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className="body mx-35 my-14">{children}</body>
    </html>
  );
}
